apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: git@github.com:hashelka/gitops
    targetRevision: main
    path: platform/eso/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true