apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake-store
    kind: SecretStore
  target:
    name: grafana-credentials
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: grafana-admin-password
        version: "v1"
    - secretKey: admin-user
      remoteRef:
        key: grafana-admin-user
        version: "v1"