apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: fake-store
  namespace: monitoring
spec:
  provider:
    fake:
      data:
        - key: grafana-admin-password
          value: "admin123"
          version: "v1"
        - key: grafana-admin-user
          value: "admin"
          version: "v1"